feat(app): Реализован функционал Todo листа
VeronikaBulaeva/ToDo-- pull request #1
Opened 2024-06-20 10:10 UTC by VeronikaBulaeva

2024-06-20 16:04 UTC, Kimiyori requested changes

2024-06-20 16:04 UTC, Kimiyori commented on src/components/toDoList/index.jsx
> +    <div style={{ display: "grid", gap: 40 }}>
инлайн стили лучше убрать. Да и вообще когда у тебя mui стоит или что-то похожее, то лучше всегда компоненты оттуда использовать, а не дефолтные

2024-06-20 16:04 UTC, Kimiyori commented on src/components/toDoList/index.jsx
> +      <Typography variant="h4" marginBlockStart="30px">
marginBlockStart можно просто на mt заменить

2024-06-20 16:04 UTC, Kimiyori commented on src/components/toDoList/index.jsx
> +    const updatedList = tasks.map((e) => {
лучше называть нормально переменные. Не e, а например task

2024-06-20 16:04 UTC, Kimiyori commented on src/components/toDoList/index.jsx
> +import Filter from "../filter/index.jsx";
лучше делать через абсолютные пути

2024-06-20 16:04 UTC, Kimiyori commented on src/components/listItem/index.jsx
> +            sx={{ textDecoration: isCheck ? "line-through" : "none" }}
isCheck && "line-through"

2024-06-20 16:04 UTC, Kimiyori commented on src/components/listItem/index.jsx
> +    <div>
опять дивы

2024-06-20 16:04 UTC, Kimiyori commented on src/components/input/index.jsx
> +  const ref = useRef(null);
по какой причине используешь ref?

2024-06-20 16:04 UTC, Kimiyori commented on src/components/input/index.jsx
> +    <div className={"filterContainer"}>
зачем класс?

2024-06-20 16:04 UTC, Kimiyori commented on src/components/input/index.jsx
> +            }
можно покороче

2024-06-20 16:04 UTC, Kimiyori commented on src/components/filter/index.jsx
> +        sx={{ p: "2px 4px", display: "flex", alignItems: "center", width: 400 }}
у mui есть свои переменные для паддинга в каждую сторону, лучше не вставлять как в голом ксс сплошную строку

2024-06-20 16:04 UTC, Kimiyori commented on src/components/input/index.jsx
> +              clearInput();
зачем при enter ты чистишь поле?

2024-06-20 16:04 UTC, Kimiyori commented on src/components/listItem/index.jsx
> +        />
при редактировании инпут выглядит точно также, как и инпут добавления таски. Измени под дизайн ну или как хочешь, но чтобы было видно что делает какая кнопка, а то сейчас кнопка сохранения изменений у таски это иконка плюсика.

2024-06-20 16:04 UTC, Kimiyori commented on src/components/toDoList/index.jsx
> +  });
почему решила не ложить в useMemo?

2024-06-20 16:05 UTC, Kimiyori commented
бтв обнаружил еще баг, что можно создать пустую таску

2024-06-20 16:06 UTC, Kimiyori commented
Также баг когда ты нажимаешь редактировать таску и сохраняешь ее без изменений

2024-06-20 16:06 UTC, Kimiyori commented
И хорошо бы прикрутить тс

2024-06-20 18:01 UTC, VeronikaBulaeva commented on src/components/input/index.jsx
> +  const ref = useRef(null);
Чтобы лишний раз не перерисовывать компонент и получить значение)

2024-06-20 18:03 UTC, VeronikaBulaeva commented on src/components/input/index.jsx
> +              clearInput();
Потому что в условии задачи сказано очищать инпут при добавление задачи.
В данном случае enter = нажатие на +, т.к. с клавиатуры так удобнее добавлять задачу

2024-06-20 18:09 UTC, VeronikaBulaeva commented on src/components/toDoList/index.jsx
> +  });
Т.к. useMemo в данном случае никакой пользы не несёт.
Придется писать в зависимости tasks и search, и количество пересчитываний будет таким же

TS не прикручен, т.к когда давали задание, Иван уточнил, что нужно сделать пока без TS
![tg](https://github.com/VeronikaBulaeva/ToDo--/assets/118721443/d9472dbe-89c1-48d4-a612-c5c553e9c885)

В чем бак при создании пустой таски?
Почему её нельзя создавать, если пользователю это нужно?

2024-06-20 18:46 UTC, VeronikaBulaeva commented on src/components/listItem/index.jsx
> +            sx={{ textDecoration: isCheck ? "line-through" : "none" }}
Я думаю, что лучше оставить тернарник, т.к. при && может быть строка или false
IDE даже предупреждает об этом
![Безымянный](https://github.com/VeronikaBulaeva/ToDo--/assets/118721443/be34c2d6-6df8-4f8d-866c-5f85d96ec67d)

2024-06-20 19:34 UTC, Kimiyori commented on src/components/toDoList/index.jsx
> +  });
жесть, я опять проспал все, значит без тса :)
а по поводу пустой таски...ну даже не знаю, я что-то не вижу как это может быть нужным, но это что я считаю. В целом, если так и планировалось, то ок

2024-06-20 19:40 UTC, Kimiyori commented on src/components/input/index.jsx
> +              clearInput();
да, но это только для инпута ввода, для редактирования это не нужно

2024-06-20 19:49 UTC, Kimiyori commented on src/components/input/index.jsx
> +  const ref = useRef(null);
так-то так, просто не вижу причины для такого для компонента с 1 действием. Но в целом ок

2024-06-20 19:52 UTC, Kimiyori commented on src/components/listItem/index.jsx
> +            sx={{ textDecoration: isCheck ? "line-through" : "none" }}
и правда, я даже раньше не знал этого, мой вскод такого не выдает)  но в целом даже с false ошибки не будет

2024-06-20 20:27 UTC, Kimiyori commented
еще баг нашел, после добавления новой таски при наличии фильтра он сбрасывается

2024-06-24 12:35 UTC, IvanKoigerov commented on src/components/listItem/index.jsx
> +            sx={{ textDecoration: isCheck ? "line-through" : "none" }}
`undefined` лучше, в таком варианте тип не изменяешь

2024-06-24 12:45 UTC, IvanKoigerov commented on src/components/filter/index.jsx
нет смысла так на папки бить мне кажется, это делается если ты рядом ещё пару файлов сосдаешь 
например 
- Filter
  - index
  - FilterInput
  - icon
и тд

А ещё обычно такие папки называют с большой буквы, тк это компонент

2024-06-24 12:45 UTC, IvanKoigerov commented on src/components/filter/index.jsx
> +        pt: "4px",
почему в px, а не цифрами

2024-06-24 12:45 UTC, IvanKoigerov commented on src/components/filter/index.jsx
> +      }}
если в sx более 3х стилей, то выносим в styled

2024-06-24 12:45 UTC, IvanKoigerov commented on src/components/filter/index.jsx
> +      }}
ну и так везде нужно пофиксить

2024-06-24 12:45 UTC, IvanKoigerov commented on src/components/filter/index.jsx
> +        pt: "4px",
ну и так везде, лучше цифрами

2024-06-24 12:45 UTC, IvanKoigerov commented on src/components/listItem/index.jsx
> +            sx={{ textDecoration: isCheck ? "line-through" : "none" }}
на всякий случай тегну @VeronikaBulaeva

2024-06-24 12:45 UTC, IvanKoigerov commented on src/components/toDoList/index.jsx
> +        <ListItem
Кто такой лист итем? не совсем понятно, лучше по сущности называть 
ToDoItem TaskItem и тд

2024-06-24 12:45 UTC, IvanKoigerov commented on src/components/toDoList/index.jsx
> +          key={`${task.text}${task.id}`}
у тебя есть id, нет смысла генерить кей ещё сильнее

2024-06-24 12:45 UTC, IvanKoigerov commented on src/components/toDoList/index.jsx
> +      setTasks([...tasks, { text: value, id: Date.now(), check: isCheck }]);
id обычно цифра, так что лучше getTime использовать

2024-06-24 13:09 UTC, VeronikaBulaeva commented on src/components/toDoList/index.jsx
> +      setTasks([...tasks, { text: value, id: Date.now(), check: isCheck }]);
не совсем поняла
Date.now() возвращает число, т.е. сейчас у меня id - это просто никогда не повторяющееся число
![datenow](https://github.com/VeronikaBulaeva/ToDo--/assets/118721443/c89f3e2e-d9ad-475f-8e58-9408bfadec98)
![datenowsc](https://github.com/VeronikaBulaeva/ToDo--/assets/118721443/e8dcd5be-ff4b-4b9a-8a1d-3db4aed08eff)

2024-06-24 14:02 UTC, IvanKoigerov commented on src/components/toDoList/index.jsx
У тебя есть проблема 

У тебя ререндеритья постоянно и поиск и форма создания, а такой ситуации не должно происходить

фильтр должен ререндериться лишь в тот момент когда ты пишешь в него, а также когда ты фильтруешь. Также когда ты вводишь значение в поиска, у тебя каждый введенный символ ререндерить компонент, а так не должно быть, тут нужно использовать дебаунс

Также у тебя ререндериться форма создания таски, когда фильтруешь или изменяешь таску, а это не круто, она должна ререндериться только когда ты ее используешь

![image](https://github.com/VeronikaBulaeva/ToDo--/assets/67396124/debe4c7a-ddf6-44b4-87b5-59c1d95a17a2)

Ререндеры можешь пофиксить с помощью нескольких вещей, но советую юзать контекст 
Отследить ререндеры можно с помощью консоль логов или реакт дев тулс

2024-06-24 14:02 UTC, IvanKoigerov commented on src/components/toDoList/index.jsx
> +      setTasks([...tasks, { text: value, id: Date.now(), check: isCheck }]);
Я ошибся тогда) соре

2024-06-24 14:02 UTC, VeronikaBulaeva commented on src/components/listItem/index.jsx
> +            sx={{ textDecoration: isCheck ? "line-through" : "none" }}
Если написать isCheck && "line-through", разве TS не будет ругаться?

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/Context.jsx
> +import React, { useState } from "react";
React не нужно импортировать, он очень много в себе содержит, так что это бэд практис

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/Context.jsx
> +};
лучше сделать дополнительный хук поверх, который будет это ошибку слать, так слишком громоздко и много кода повторяешь

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/Context.jsx
Лучше все провайдеры разбивать по разным файлам

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/Filter.jsx
> +        onChange={debounce(onSearch)}
debounce лучше написать в onSearch

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/Input.jsx
> +  };
может в callback обернуть, чтобы никогда не ререндерилась эта функция

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/ToDoList.jsx
> +          }}
можешь писать просто `onClickIcon={handleUpdateText}`

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/ToDoList.jsx
> +          }}
Удалять по index странно очень, удаляем по id

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/ToDoList.jsx
> +          }}
onClick не понятно на что onClick, вообще не говорящее название

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/ToDoList.jsx
> +          }}
onClickIcon не понятно на что onClickIcon, вообще не говорящее название

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/ToDoList.jsx
> +      </Typography>
лучше эти вещи в родятеля выносить и сделать так этот компонент, чтобы он только список тудух возвращал

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/ToDoList.jsx
> +  });
У тебя при каждом ререндере это происходит, не круто

2024-06-27 16:04 UTC, IvanKoigerov commented on src/components/ToDoItem.jsx
> +import Input from "src/components/Input.jsx";
Тоже нужно назвать как-то читабельнее

2024-06-27 17:10 UTC, VeronikaBulaeva commented on src/components/Filter.jsx
> +        onChange={debounce(onSearch)}
Мне кажется, что лучше её выносить, чтобы потом использовать в других местах?

2024-07-01 11:57 UTC, merged